spring:
    data:
        mongodb:
            uri: mongodb://root:example@localhost:27017/?authMechanism=SCRAM-SHA-256
            database: chat_app_database
    application:
        name: chatApp

logging:
    level:
        org.springframework.data.mongodb.core.MongoTemplate: TRACE
        org.springframework.security: TRACE

jwt:
    secret: hehejerin


